print(' ')
print(' ')
print(' ')
print(' Probando nuevos cambios con git')
<<<<<<< HEAD
print(' ')
print(' ')
print(' ')
print(' Este es nuev cambio al proyecto para probar')
print(' ')
print(' ')
print(' ')
print(' Hola hola probando probando SI SI  jijijijiji')
print(' ')
print(' ')
print(' ')
print(' Nuevo letro mir miraaaaaa.......')
print(' el pollito reponedor ')
=======
>>>>>>> 9179f3cbadbbc5fef46b94bdbced1abf817aeb63
print('esto esta aqui ')